name: 'umbli'
description: 'Runs popular linters against your project files'
inputs:
  config:  # id of input
    description: 'The path to your code'
    required: false
    default: '/github/workspace/.umbli.sh'
  mode:
    description: 'Linter mode'
    required: false
    default: 'loose'  
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.mode }}
