name: Build and Publish Docker Image
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish master to Registry
      uses: HurricanKai/Publish-Docker-Github-Action@master
      with:
        name: epicfile/umbli
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Publish tag to Registry    
      if: contains(github.ref, 'refs/tags/v')
      with:
        name: epicfile/umbli
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tagging: true
